INSERT INTO province(name,code) VALUES ('Aceh (NAD)','11');
INSERT INTO province(name,code) VALUES ('Bali','51');
INSERT INTO province(name,code) VALUES ('Banten','36');
INSERT INTO province(name,code) VALUES ('Bengkulu','17');
INSERT INTO province(name,code) VALUES ('DI Yogyakarta','34');
INSERT INTO province(name,code) VALUES ('DKI Jakarta','31');
INSERT INTO province(name,code) VALUES ('Gorontalo','75');
INSERT INTO province(name,code) VALUES ('Jambi','15');
INSERT INTO province(name,code) VALUES ('Jawa Barat','32');
INSERT INTO province(name,code) VALUES ('Jawa Tengah','33');
INSERT INTO province(name,code) VALUES ('Jawa Timur','35');
INSERT INTO province(name,code) VALUES ('Kalimantan Barat','61');
INSERT INTO province(name,code) VALUES ('Kalimantan Selatan','63');
INSERT INTO province(name,code) VALUES ('Kalimantan Tengah','62');
INSERT INTO province(name,code) VALUES ('Kalimantan Timur','64');
INSERT INTO province(name,code) VALUES ('Kalimantan Utara','65');
INSERT INTO province(name,code) VALUES ('Kepulauan Bangka Belitung','19');
INSERT INTO province(name,code) VALUES ('Kepulauan Riau','21');
INSERT INTO province(name,code) VALUES ('Lampung','18');
INSERT INTO province(name,code) VALUES ('Maluku','81');
INSERT INTO province(name,code) VALUES ('Maluku Utara','82');
INSERT INTO province(name,code) VALUES ('Nusa Tenggara Barat (NTB)','52');
INSERT INTO province(name,code) VALUES ('Nusa Tenggara Timur (NTT)','53');
INSERT INTO province(name,code) VALUES ('Papua','91');
INSERT INTO province(name,code) VALUES ('Papua Barat','92');
INSERT INTO province(name,code) VALUES ('Papua Pegunungan','95');
INSERT INTO province(name,code) VALUES ('Papua Selatan','93');
INSERT INTO province(name,code) VALUES ('Papua Tengah','94');
INSERT INTO province(name,code) VALUES ('Riau','14');
INSERT INTO province(name,code) VALUES ('Sulawesi Barat','76');
INSERT INTO province(name,code) VALUES ('Sulawesi Selatan','73');
INSERT INTO province(name,code) VALUES ('Sulawesi Tengah','72');
INSERT INTO province(name,code) VALUES ('Sulawesi Tenggara','74');
INSERT INTO province(name,code) VALUES ('Sulawesi Utara','71');
INSERT INTO province(name,code) VALUES ('Sumatera Barat','13');
INSERT INTO province(name,code) VALUES ('Sumatera Selatan','16');
INSERT INTO province(name,code) VALUES ('Sumatera Utara','12');
