INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Barat','11','05','1105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Barat Daya','11','12','1112');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Besar','11','06','1106');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Jaya','11','14','1114');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Selatan','11','01','1101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Singkil','11','10','1110');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Tamiang','11','16','1116');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Tengah','11','04','1104');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Tenggara','11','02','1102');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Timur','11','03','1103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Aceh Utara','11','08','1108');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Agam','13','06','1306');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Alor','53','05','5305');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Ambon','81','71','8171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Asahan','12','09','1209');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Asmat','93','04','9304');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Badung','51','03','5103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Balangan','63','11','6311');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Balikpapan','64','71','6471');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Banda Aceh','11','71','1171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bandar Lampung','18','71','1871');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bandung','32','73','3273');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bandung','32','04','3204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bandung Barat','32','17','3217');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banggai','72','01','7201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banggai Kepulauan','72','07','7207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banggai Laut','72','11','7211');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bangka','19','01','1901');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bangka Barat','19','05','1905');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bangka Selatan','19','03','1903');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bangka Tengah','19','04','1904');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bangkalan','35','26','3526');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bangli','51','06','5106');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Banjar','32','79','3279');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banjar','63','03','6303');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Banjarbaru','63','72','6372');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Banjarmasin','63','71','6371');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banjarnegara','33','04','3304');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bantaeng','73','03','7303');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bantul','34','02','3402');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banyuasin','16','07','1607');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banyumas','33','02','3302');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Banyuwangi','35','10','3510');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Barito Kuala','63','04','6304');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Barito Selatan','62','04','6204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Barito Timur','62','13','6213');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Barito Utara','62','05','6205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Barru','73','11','7311');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Batam','21','71','2171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Batang','33','25','3325');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Batanghari','15','04','1504');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Batu','35','79','3579');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Batu Bara','12','19','1219');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bau Bau','74','72','7472');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bekasi','32','75','3275');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bekasi','32','16','3216');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Belitung','19','02','1902');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Belitung Timur','19','06','1906');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Belu','53','04','5304');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bener Meriah','11','17','1117');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bengkalis','14','03','1403');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bengkayang','61','07','6107');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bengkulu','17','71','1771');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bengkulu Selatan','17','01','1701');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bengkulu Tengah','17','09','1709');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bengkulu Utara','17','03','1703');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Berau','64','03','6403');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Biak Numfor','91','06','9106');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bima','52','06','5206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bima','52','72','5272');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Binjai','12','75','1275');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bintan','21','01','2101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bireuen','11','11','1111');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bitung','71','72','7172');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Blitar','35','05','3505');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Blitar','35','72','3572');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Blora','33','16','3316');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Boalemo','75','02','7502');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bogor','32','01','3201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bogor','32','71','3271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bojonegoro','35','22','3522');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bolaang Mongondow','71','01','7101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bolaang Mongondow Selatan','71','11','7111');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bolaang Mongondow Timur','71','10','7110');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bolaang Mongondow Utara','71','08','7108');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bombana','74','06','7406');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bondowoso','35','11','3511');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bone','73','08','7308');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bone Bolango','75','03','7503');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bontang','64','74','6474');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Boven Digoel','93','02','9302');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Boyolali','33','09','3309');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Brebes','33','29','3329');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Bukittinggi','13','75','1375');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buleleng','51','08','5108');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bulukumba','73','02','7302');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bulungan','65','01','6501');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Bungo','15','08','1508');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buol','72','05','7205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buru','81','04','8104');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buru Selatan','81','09','8109');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buton','74','04','7404');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buton Selatan','74','15','7415');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buton Tengah','74','14','7414');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Buton Utara','74','10','7410');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ciamis','32','07','3207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Cianjur','32','03','3203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Cilacap','33','01','3301');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Cilegon','36','72','3672');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Cimahi','32','77','3277');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Cirebon','32','74','3274');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Cirebon','32','09','3209');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Dairi','12','11','1211');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Deiyai','94','08','9408');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Deli Serdang','12','07','1207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Demak','33','21','3321');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Denpasar','51','71','5171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Depok','32','76','3276');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Dharmasraya','13','10','1310');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Dogiyai','94','06','9406');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Dompu','52','05','5205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Donggala','72','03','7203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Dumai','14','72','1472');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Empat Lawang','16','11','1611');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ende','53','08','5308');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Enrekang','73','16','7316');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Fak Fak','92','03','9203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Flores Timur','53','06','5306');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Garut','32','05','3205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gayo Lues','11','13','1113');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gianyar','51','04','5104');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gorontalo','75','01','7501');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Gorontalo','75','71','7571');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gorontalo Utara','75','05','7505');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gowa','73','06','7306');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gresik','35','25','3525');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Grobogan','33','15','3315');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gunung Mas','62','10','6210');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Gunungkidul','34','03','3403');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Gunungsitoli','12','78','1278');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Halmahera Barat','82','01','8201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Halmahera Selatan','82','04','8204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Halmahera Tengah','82','02','8202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Halmahera Timur','82','06','8206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Halmahera Utara','82','03','8203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Hulu Sungai Selatan','63','06','6306');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Hulu Sungai Tengah','63','07','6307');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Hulu Sungai Utara','63','08','6308');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Humbang Hasundutan','12','16','1216');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Indragiri Hilir','14','04','1404');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Indragiri Hulu','14','02','1402');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Indramayu','32','12','3212');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Intan Jaya','94','07','9407');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jakarta Barat','31','73','3173');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jakarta Pusat','31','71','3171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jakarta Selatan','31','74','3174');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jakarta Timur','31','75','3175');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jakarta Utara','31','72','3172');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jambi','15','71','1571');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jayapura','91','03','9103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Jayapura','91','71','9171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jayawijaya','95','01','9501');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jember','35','09','3509');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jembrana','51','01','5101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jeneponto','73','04','7304');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jepara','33','20','3320');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Jombang','35','17','3517');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kaimana','92','08','9208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kampar','14','01','1401');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kapuas','62','03','6203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kapuas Hulu','61','06','6106');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Karanganyar','33','13','3313');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Karangasem','51','07','5107');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Karawang','32','15','3215');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Karimun','21','02','2102');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Karo','12','06','1206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Katingan','62','06','6206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kaur','17','04','1704');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kayong Utara','61','11','6111');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kebumen','33','05','3305');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kediri','35','06','3506');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Kediri','35','71','3571');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Keerom','91','11','9111');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kendal','33','24','3324');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Kendari','74','71','7471');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepahiang','17','08','1708');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Anambas','21','05','2105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Aru','81','07','8107');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Mentawai','13','09','1309');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Meranti','14','10','1410');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Sangihe','71','03','7103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Selayar','73','01','7301');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Seribu','31','01','3101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Siau Tagulandang Biaro (Sitaro)','71','09','7109');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Sula','82','05','8205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Talaud','71','04','7104');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Tanimbar (Maluku Tenggara Barat)','81','03','8103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kepulauan Yapen','91','05','9105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kerinci','15','01','1501');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ketapang','61','04','6104');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Klaten','33','10','3310');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Klungkung','51','05','5105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kolaka','74','01','7401');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kolaka Timur','74','11','7411');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kolaka Utara','74','08','7408');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Konawe','74','02','7402');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Konawe Kepulauan','74','12','7412');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Konawe Selatan','74','05','7405');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Konawe Utara','74','09','7409');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kotabaru','63','02','6302');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Kotamobagu','71','74','7174');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kotawaringin Barat','62','01','6201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kotawaringin Timur','62','02','6202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kuantan Singingi','14','09','1409');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kubu Raya','61','12','6112');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kudus','33','19','3319');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kulon Progo','34','01','3401');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kuningan','32','08','3208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kupang','53','01','5301');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Kupang','53','71','5371');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kutai Barat','64','07','6407');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kutai Kartanegara','64','02','6402');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Kutai Timur','64','08','6408');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Labuhanbatu','12','10','1210');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Labuhanbatu Selatan','12','22','1222');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Labuhanbatu Utara','12','23','1223');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lahat','16','04','1604');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lamandau','62','09','6209');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lamongan','35','24','3524');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lampung Barat','18','04','1804');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lampung Selatan','18','01','1801');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lampung Tengah','18','02','1802');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lampung Timur','18','07','1807');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lampung Utara','18','03','1803');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Landak','61','08','6108');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Langkat','12','05','1205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Langsa','11','74','1174');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lanny Jaya','95','07','9507');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lebak','36','02','3602');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lebong','17','07','1707');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lembata','53','13','5313');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Lhokseumawe','11','73','1173');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lima Puluh Kota','13','07','1307');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lingga','21','04','2104');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lombok Barat','52','01','5201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lombok Tengah','52','02','5202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lombok Timur','52','03','5203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lombok Utara','52','08','5208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Lubuk Linggau','16','73','1673');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Lumajang','35','08','3508');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Luwu','73','17','7317');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Luwu Timur','73','24','7324');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Luwu Utara','73','22','7322');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Madiun','35','19','3519');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Madiun','35','77','3577');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Magelang','33','08','3308');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Magelang','33','71','3371');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Magetan','35','20','3520');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mahakam Ulu','64','11','6411');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Majalengka','32','10','3210');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Majene','76','05','7605');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Makassar','73','71','7371');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Malaka','53','21','5321');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Malang','35','07','3507');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Malang','35','73','3573');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Malinau','65','02','6502');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Maluku Barat Daya','81','08','8108');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Maluku Tengah','81','01','8101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Maluku Tenggara','81','02','8102');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mamasa','76','03','7603');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mamberamo Raya','91','20','9120');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mamberamo Tengah','95','05','9505');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mamuju','76','02','7602');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mamuju Tengah','76','06','7606');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Manado','71','71','7171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mandailing Natal','12','13','1213');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Manggarai','53','10','5310');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Manggarai Barat','53','15','5315');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Manggarai Timur','53','19','5319');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Manokwari','92','02','9202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Manokwari Selatan','92','11','9211');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mappi','93','03','9303');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Maros','73','09','7309');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Mataram','52','71','5271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Maybrat','92','10','9210');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Medan','12','71','1271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Melawi','61','10','6110');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mempawah','61','02','6102');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Merangin','15','02','1502');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Merauke','93','01','9301');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mesuji','18','11','1811');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Metro','18','72','1872');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mimika','94','04','9404');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Minahasa','71','02','7102');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Minahasa Selatan','71','05','7105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Minahasa Tenggara','71','07','7107');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Minahasa Utara','71','06','7106');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Mojokerto','35','16','3516');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Mojokerto','35','76','3576');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Morowali','72','06','7206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Morowali Utara','72','12','7212');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Muara Enim','16','03','1603');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Muaro Jambi','15','05','1505');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Muko Muko','17','06','1706');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Muna','74','03','7403');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Muna Barat','74','13','7413');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Murung Raya','62','12','6212');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Musi Banyuasin','16','06','1606');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Musi Rawas','16','05','1605');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Musi Rawas Utara','16','13','1613');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nabire','94','01','9401');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nagan Raya','11','15','1115');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nagekeo','53','16','5316');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Natuna','21','03','2103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nduga','95','08','9508');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ngada','53','09','5309');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nganjuk','35','18','3518');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ngawi','35','21','3521');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nias','12','04','1204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nias Barat','12','25','1225');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nias Selatan','12','14','1214');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nias Utara','12','24','1224');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Nunukan','65','03','6503');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ogan Ilir','16','10','1610');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ogan Komering Ilir','16','02','1602');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ogan Komering Ulu','16','01','1601');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ogan Komering Ulu Selatan','16','09','1609');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ogan Komering Ulu Timur','16','08','1608');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pacitan','35','01','3501');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Padang','13','71','1371');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Padang Lawas','12','21','1221');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Padang Lawas Utara','12','20','1220');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Padang Panjang','13','74','1374');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Padang Pariaman','13','05','1305');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Padangsidimpuan','12','77','1277');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pagar Alam','16','72','1672');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pahuwato','75','04','7504');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pakpak Bharat','12','15','1215');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Palangkaraya','62','71','6271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Palembang','16','71','1671');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Palopo','73','73','7373');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Palu','72','71','7271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pamekasan','35','28','3528');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pandeglang','36','01','3601');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pangandaran','32','18','3218');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pangkajene Kepulauan','73','10','7310');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pangkal Pinang','19','71','1971');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Paniai','94','03','9403');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pare Pare','73','72','7372');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pariaman','13','77','1377');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Parigi Moutong','72','08','7208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pasaman','13','08','1308');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pasaman Barat','13','12','1312');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pasangkayu (Mamuju Utara)','76','01','7601');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Paser','64','01','6401');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pasuruan','35','14','3514');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pasuruan','35','75','3575');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pati','33','18','3318');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Payakumbuh','13','76','1376');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pegunungan Arfak','92','12','9212');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pegunungan Bintang','95','02','9502');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pekalongan','33','26','3326');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pekalongan','33','75','3375');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pekanbaru','14','71','1471');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pelalawan','14','05','1405');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pemalang','33','27','3327');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pematangsiantar','12','72','1272');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Penajam Paser Utara','64','09','6409');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Penukal Abab Lematang Ilir','16','12','1612');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pesawaran','18','09','1809');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pesisir Barat','18','13','1813');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pesisir Selatan','13','01','1301');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pidie','11','07','1107');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pidie Jaya','11','18','1118');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pinrang','73','15','7315');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Polewali Mandar','76','04','7604');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Ponorogo','35','02','3502');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Pontianak','61','71','6171');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Poso','72','02','7202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Prabumulih','16','74','1674');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pringsewu','18','10','1810');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Probolinggo','35','13','3513');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Probolinggo','35','74','3574');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pulang Pisau','62','11','6211');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pulau Morotai','82','07','8207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Pulau Taliabu','82','08','8208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Puncak','94','05','9405');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Puncak Jaya','94','02','9402');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Purbalingga','33','03','3303');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Purwakarta','32','14','3214');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Purworejo','33','06','3306');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Raja Ampat','92','05','9205');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Rejang Lebong','17','02','1702');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Rembang','33','17','3317');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Rokan Hilir','14','07','1407');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Rokan Hulu','14','06','1406');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Rote Ndao','53','14','5314');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Sabang','11','72','1172');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sabu Raijua','53','20','5320');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Salatiga','33','73','3373');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Samarinda','64','72','6472');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sambas','61','01','6101');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Samosir','12','17','1217');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sampang','35','27','3527');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sanggau','61','03','6103');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sarmi','91','10','9110');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sarolangun','15','03','1503');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Sawahlunto','13','73','1373');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sekadau','61','09','6109');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Seluma','17','05','1705');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Semarang','33','22','3322');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Semarang','33','74','3374');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Seram Bagian Barat','81','06','8106');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Seram Bagian Timur','81','05','8105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Serang','36','73','3673');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Serang','36','04','3604');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Serdang Bedagai','12','18','1218');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Seruyan','62','07','6207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Siak','14','08','1408');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Sibolga','12','73','1273');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sidenreng Rappang','73','14','7314');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sidoarjo','35','15','3515');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sigi','72','10','7210');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sijunjung','13','03','1303');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sikka','53','07','5307');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Simalungun','12','08','1208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Simeulue','11','09','1109');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Singkawang','61','72','6172');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sinjai','73','07','7307');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sintang','61','05','6105');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Situbondo','35','12','3512');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sleman','34','04','3404');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Solok','13','02','1302');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Solok','13','72','1372');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Solok Selatan','13','11','1311');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Soppeng','73','12','7312');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sorong','92','01','9201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Sorong','92','71','9271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sorong Selatan','92','04','9204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sragen','33','14','3314');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Subang','32','13','3213');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Subulussalam','11','75','1175');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Sukabumi','32','72','3272');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sukabumi','32','02','3202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sukamara','62','08','6208');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sukoharjo','33','11','3311');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumba Barat','53','12','5312');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumba Barat Daya','53','18','5318');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumba Tengah','53','17','5317');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumba Timur','53','11','5311');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumbawa','52','04','5204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumbawa Barat','52','07','5207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumedang','32','11','3211');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Sumenep','35','29','3529');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Sungai Penuh','15','72','1572');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Supiori','91','19','9119');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Surabaya','35','78','3578');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Surakarta','33','72','3372');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tabalong','63','09','6309');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tabanan','51','02','5102');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Takalar','73','05','7305');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tambrauw','92','09','9209');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tana Tidung','65','04','6504');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tana Toraja','73','18','7318');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tanah Bumbu','63','10','6310');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tanah Datar','13','04','1304');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tanah Laut','63','01','6301');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tangerang','36','71','3671');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tangerang','36','03','3603');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tangerang Selatan','36','74','3674');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tanggamus','18','06','1806');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tanjung Balai','12','74','1274');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tanjung Jabung Barat','15','06','1506');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tanjung Jabung Timur','15','07','1507');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tanjung Pinang','21','72','2172');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tapanuli Selatan','12','03','1203');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tapanuli Tengah','12','01','1201');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tapanuli Utara','12','02','1202');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tapin','63','05','6305');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tarakan','65','71','6571');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tasikmalaya','32','78','3278');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tasikmalaya','32','06','3206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tebing Tinggi','12','76','1276');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tebo','15','09','1509');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tegal','33','28','3328');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tegal','33','76','3376');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Teluk Bintuni','92','06','9206');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Teluk Wondama','92','07','9207');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Temanggung','33','23','3323');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Ternate','82','71','8271');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tidore Kepulauan','82','72','8272');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Timor Tengah Selatan','53','02','5302');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Timor Tengah Utara','53','03','5303');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Toba','12','12','1212');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tojo Una Una','72','09','7209');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Toli Toli','72','04','7204');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tolikara','95','04','9504');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tomohon','71','73','7173');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Toraja Utara','73','26','7326');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Trenggalek','35','03','3503');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Tual','81','72','8172');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tuban','35','23','3523');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tulang Bawang','18','05','1805');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tulang Bawang Barat','18','12','1812');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Tulungagung','35','04','3504');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Wajo','73','13','7313');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Wakatobi','74','07','7407');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Waropen','91','15','9115');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Way Kanan','18','08','1808');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Wonogiri','33','12','3312');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Wonosobo','33','07','3307');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Yahukimo','95','03','9503');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kabupaten','Yalimo','95','06','9506');
INSERT INTO regency(type,name,province_code,self_code,code) VALUES ('Kota','Yogyakarta','34','71','3471');
